/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *bksp;
  GtkWidget *one;
  GtkWidget *dot;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *plus;
  GtkWidget *minus;
  GtkWidget *equals;
  GtkWidget *zero;
  GtkWidget *six;
  GtkWidget *mul;
  GtkWidget *div;
  GtkWidget *five;
  GtkWidget *CE;
  GtkWidget *_;
  GtkWidget *nine;
  GtkWidget *eight;
  GtkWidget *seven;
  GtkWidget *four;
  GtkWidget *Clr;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window2), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 104, 24);
  gtk_widget_set_size_request (entry1, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  bksp = gtk_button_new_with_mnemonic (_("bksp"));
  gtk_widget_show (bksp);
  gtk_fixed_put (GTK_FIXED (fixed3), bksp, 20, 88);
  gtk_widget_set_size_request (bksp, 79, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed3), one, 20, 238);
  gtk_widget_set_size_request (one, 79, 29);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed3), dot, 20, 288);
  gtk_widget_set_size_request (dot, 79, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed3), two, 120, 238);
  gtk_widget_set_size_request (two, 79, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed3), three, 220, 238);
  gtk_widget_set_size_request (three, 79, 29);

  plus = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (plus);
  gtk_fixed_put (GTK_FIXED (fixed3), plus, 320, 238);
  gtk_widget_set_size_request (plus, 79, 29);

  minus = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (minus);
  gtk_fixed_put (GTK_FIXED (fixed3), minus, 320, 288);
  gtk_widget_set_size_request (minus, 79, 29);

  equals = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equals);
  gtk_fixed_put (GTK_FIXED (fixed3), equals, 220, 288);
  gtk_widget_set_size_request (equals, 79, 29);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed3), zero, 120, 288);
  gtk_widget_set_size_request (zero, 79, 29);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed3), six, 220, 188);
  gtk_widget_set_size_request (six, 79, 29);

  mul = gtk_button_new_with_mnemonic (_("x"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed3), mul, 320, 188);
  gtk_widget_set_size_request (mul, 79, 29);

  div = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (div);
  gtk_fixed_put (GTK_FIXED (fixed3), div, 320, 138);
  gtk_widget_set_size_request (div, 79, 29);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed3), five, 120, 188);
  gtk_widget_set_size_request (five, 79, 29);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed3), CE, 120, 88);
  gtk_widget_set_size_request (CE, 79, 29);

  _ = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed3), _, 320, 88);
  gtk_widget_set_size_request (_, 79, 29);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed3), nine, 220, 138);
  gtk_widget_set_size_request (nine, 79, 29);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed3), eight, 120, 138);
  gtk_widget_set_size_request (eight, 79, 29);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed3), seven, 20, 138);
  gtk_widget_set_size_request (seven, 79, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed3), four, 20, 188);
  gtk_widget_set_size_request (four, 79, 29);

  Clr = gtk_button_new_with_mnemonic (_("Clr"));
  gtk_widget_show (Clr);
  gtk_fixed_put (GTK_FIXED (fixed3), Clr, 220, 88);
  gtk_widget_set_size_request (Clr, 79, 29);

  g_signal_connect ((gpointer) bksp, "clicked",
                    G_CALLBACK (on_bksp_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) plus, "clicked",
                    G_CALLBACK (on_plus_clicked),
                    NULL);
  g_signal_connect ((gpointer) minus, "clicked",
                    G_CALLBACK (on_minus_clicked),
                    NULL);
  g_signal_connect ((gpointer) equals, "clicked",
                    G_CALLBACK (on_equals_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) div, "clicked",
                    G_CALLBACK (on_div_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) Clr, "clicked",
                    G_CALLBACK (on_Clr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, bksp, "bksp");
  GLADE_HOOKUP_OBJECT (window2, one, "one");
  GLADE_HOOKUP_OBJECT (window2, dot, "dot");
  GLADE_HOOKUP_OBJECT (window2, two, "two");
  GLADE_HOOKUP_OBJECT (window2, three, "three");
  GLADE_HOOKUP_OBJECT (window2, plus, "plus");
  GLADE_HOOKUP_OBJECT (window2, minus, "minus");
  GLADE_HOOKUP_OBJECT (window2, equals, "equals");
  GLADE_HOOKUP_OBJECT (window2, zero, "zero");
  GLADE_HOOKUP_OBJECT (window2, six, "six");
  GLADE_HOOKUP_OBJECT (window2, mul, "mul");
  GLADE_HOOKUP_OBJECT (window2, div, "div");
  GLADE_HOOKUP_OBJECT (window2, five, "five");
  GLADE_HOOKUP_OBJECT (window2, CE, "CE");
  GLADE_HOOKUP_OBJECT (window2, _, "_");
  GLADE_HOOKUP_OBJECT (window2, nine, "nine");
  GLADE_HOOKUP_OBJECT (window2, eight, "eight");
  GLADE_HOOKUP_OBJECT (window2, seven, "seven");
  GLADE_HOOKUP_OBJECT (window2, four, "four");
  GLADE_HOOKUP_OBJECT (window2, Clr, "Clr");

  return window2;
}

